server:
  port: 80
  max-http-header-size: 10000000

#数据源的配置
spring:
  datasource:
    username: root
    password: 116116lai
    url: jdbc:mysql://localhost:3306/goods_market?serverTimezone=GMT&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名法

  mapper-locations: classpath:mybatis/mappers/*.xml  #扫描xml文件的路径

